pppoe: fix #189
accel-ppp/accel-ppp pull request #190
Opened 2024-09-04 16:47 UTC by Tokarak

Tested. Now it is possible to use chap-secrets authentication with pppoe.

2024-09-04 16:54 UTC, svlobanov commented
Does it work if accel-ppp is built without radius support?

2024-09-04 18:46 UTC, Tokarak commented
> Does it work if accel-ppp is built without radius support?

Correct, it doesn't build. Tested on Rocky Linux. Closing the pr and moving the conversation back to the linked issue.

2024-09-04 19:35 UTC, svlobanov requested changes
Please squash two commits into one. Please use commit message like this one https://github.com/accel-ppp/accel-ppp/commit/26ebe599c3f1241022038d4b3f709410074876c5

2024-09-04 20:32 UTC, svlobanov approved these changes
LGTM

2024-09-05 07:43 UTC, merged

2024-09-05 08:25 UTC, svlobanov commented
Unfortunately, this approach doesn't work. pppoe+chap_secret test fails https://github.com/accel-ppp/accel-ppp/actions/runs/10716066985/job/29712772260

It happens because `TARGET_LINK_LIBRARIES(pppoe vlan-mon connlimit radius)` does the following thing: libradius.so is loaded when libpppoe.so is loaded. In this case, accel-ppp works with radius and ignores chap-secrets config. That's why pppoe+chap_secret fails.

```
 ldd /usr/lib/accel-ppp/libpppoe.so 
        linux-vdso.so.1 (0x0000fd27cfbf7000)
        libvlan-mon.so => /usr/lib/accel-ppp/libvlan-mon.so (0x0000fd27cfb50000)
        libconnlimit.so => /usr/lib/accel-ppp/libconnlimit.so (0x0000fd27cfb20000)
        libradius.so => /usr/lib/accel-ppp/libradius.so (0x0000fd27cfae0000)
        libc.so.6 => /lib/aarch64-linux-gnu/libc.so.6 (0x0000fd27cf920000)
        /lib/ld-linux-aarch64.so.1 (0x0000fd27cfbba000)
        libluasupp.so => /usr/lib/accel-ppp/libluasupp.so (0x0000fd27cf8f0000)
        liblua5.1.so.0 => /lib/aarch64-linux-gnu/liblua5.1.so.0 (0x0000fd27cf890000)
        libm.so.6 => /lib/aarch64-linux-gnu/libm.so.6 (0x0000fd27cf7e0000)
```

I'm reverting this commit. We need to find another way manage plugins loading issue on musl libc.