L2TP include calling number to calling station ID RA
accel-ppp/accel-ppp pull request #225
Opened 2024-12-05 11:13 UTC by ykholod

2024-12-05 14:30 UTC, svlobanov requested changes
Please rebase on master before applying your changes

2024-12-05 14:30 UTC, svlobanov commented on accel-pppd/ctrl/l2tp/l2tp.c
> -	res = connect(conn->hnd.fd, (struct sockaddr*)&conn->peer_addr, sizeof(conn->peer_addr));
Please rebase on master before applying your changes

2024-12-05 15:24 UTC, ykholod commented on accel-pppd/ctrl/l2tp/l2tp.c
> -	res = connect(conn->hnd.fd, (struct sockaddr*)&conn->peer_addr, sizeof(conn->peer_addr));
Done

2024-12-10 08:06 UTC, ykholod commented
@nuclearcat @DmitriyEshenko @svlobanov 
Could you please review this PR again? Does it need any other updates before merge?

2024-12-12 20:04 UTC, DmitriyEshenko approved these changes

2024-12-12 20:15 UTC, sever-sever approved these changes

2025-01-09 21:04 UTC, merged