Add vrf support for Framed-Route and Framed-IPv6-Route
accel-ppp/accel-ppp pull request #93
Opened 2023-06-29 08:26 UTC by ChrisHills463

With this patch any routes specified by the radius server will be added to the vrf named by `Accel-VRF-Name`. Previously the routes would be added to the main table.

2025-03-12 21:44 UTC, sever-sever commented
@ChrisHills463 Did you check it for IPv6-PD? 
The similar case https://vyos.dev/T7240

2025-03-13 08:07 UTC, ChrisHills463 commented
> @ChrisHills463 Did you check it for IPv6-PD? The similar case https://vyos.dev/T7240

Sorry it has been so long, I cannot remember if I tested it.

2025-03-13 11:34 UTC, sever-sever commented
> Sorry it has been so long, I cannot remember if I tested it.

I checked it, It only fixes the `Framed-Route, Framed-IPv6-Route`  but does not the IPv6-PD SLAAC.
Thanks

2025-03-13 11:37 UTC, ChrisHills463 commented
> I checked it, It only fixes the `Framed-Route, Framed-IPv6-Route` but does not the IPv6-PD SLAAC. Thanks

It shouldn't be too hard to fix, I will take a look when I get chance this week or next.

2025-04-29 08:12 UTC, AndriiFullroot commented on accel-pppd/libnetlink/iputils.c
> +int __export iproute_del(int ifindex, in_addr_t src, in_addr_t dst, in_addr_t gw, int proto, int mask, uint32_t prio, const char *vrf_name)
Need to add `ipvrf_get_table()` routine here.

2025-04-29 08:12 UTC, AndriiFullroot commented on accel-pppd/libnetlink/iputils.c
> +int __export ip6route_del(int ifindex, const struct in6_addr *dst, int pref_len, const struct in6_addr *gw, int proto, uint32_t prio, const char *vrf_name)
Need to add `ipvrf_get_table()` routine here.

2025-04-29 08:12 UTC, AndriiFullroot commented on accel-pppd/libnetlink/iputils.h
> +#ifdef HAVE_VRF
Same for IPv4 or remove HAVE_VRF here.

2025-04-29 10:14 UTC, ChrisHills463 commented on accel-pppd/libnetlink/iputils.c
> +int __export iproute_del(int ifindex, in_addr_t src, in_addr_t dst, in_addr_t gw, int proto, int mask, uint32_t prio, const char *vrf_name)
Should be fixed in 26c4d8a7

2025-04-29 10:14 UTC, ChrisHills463 commented on accel-pppd/libnetlink/iputils.c
> +int __export ip6route_del(int ifindex, const struct in6_addr *dst, int pref_len, const struct in6_addr *gw, int proto, uint32_t prio, const char *vrf_name)
Should be fixed in 26c4d8a7

2025-04-29 10:14 UTC, ChrisHills463 commented on accel-pppd/libnetlink/iputils.h
> +#ifdef HAVE_VRF
Should be fixed in 26c4d8a7

2025-04-29 14:29 UTC, themiron commented on accel-pppd/ifcfg.c
> +#endif
there's no need for ifdef all around the code, just use one function with one ifdef inside it

2025-04-29 15:31 UTC, themiron requested changes

2025-04-29 15:31 UTC, themiron commented on accel-pppd/ipv6/dhcpv6.c
> +#endif
same issue, no need for ifdef, use one function instead

2025-04-29 15:31 UTC, themiron commented on accel-pppd/ipv6/dhcpv6.c
> +#endif
same issue, no need for ifdef, use one function instead

2025-04-29 15:31 UTC, themiron commented on accel-pppd/libnetlink/iputils.c
> +	__u32 rt_table = RT_TABLE_MAIN;
__u32 although is technically ok, but invalid for style. project uses stdint names, see above uint32_t
please move variable definitions to function top

2025-04-29 15:31 UTC, themiron commented on accel-pppd/libnetlink/iputils.c
> +	__u32 rt_table = ipvrf_get_table(vrf_name);
what about error handling? on error there'll be main table, isn't it security issue then?

2025-04-29 15:31 UTC, themiron commented on accel-pppd/libnetlink/iputils.h
> +#endif
is there any reason to preserve functions w/o vrf_name?

2025-04-29 15:31 UTC, themiron commented on accel-pppd/libnetlink/rt_names.c
> +		if (sscanf(p, "0x%x %s\n", id, namebuf) != 2 &&
unsafe, can lead to buffer overflow

2025-04-29 15:31 UTC, themiron commented on accel-pppd/libnetlink/rt_names.c
> +		return;
suggest to return value 0 for success, and -1 for error to let know clients about error

2025-04-29 15:31 UTC, themiron commented on accel-pppd/libnetlink/rt_names.c
> +		entry = malloc(sizeof(*entry));
alloc in runtime is not safe, can lead to oom of running process. can we allocate init early, on startup time?

2025-04-29 15:31 UTC, themiron commented on accel-pppd/libnetlink/rt_names.c
> +		return;
same issue, what if some any error has occurred? let's return retval to let client known about (and use it, of course)

2025-04-29 15:31 UTC, themiron commented on accel-pppd/libnetlink/iputils.c
> +	if (strcmp(RTA_DATA(li[IFLA_INFO_KIND]), "vrf"))
strcmp is unsafe, consider strncmp or strlcmp

2025-04-29 15:31 UTC, themiron commented on accel-pppd/libnetlink/rt_names.c
> +		if (strcmp(de->d_name + len - 5, ".conf"))
strcmp is unsafe, consider strncmp or strlcmp

2025-04-29 15:31 UTC, themiron commented on accel-pppd/libnetlink/rt_names.c
> +	if (cache && strcmp(cache, arg) == 0) {
strcmp is unsafe, consider strncmp or strlcmp

2025-04-29 15:31 UTC, themiron commented on accel-pppd/libnetlink/rt_names.c
> +		while (entry && strcmp(entry->name, arg))
strcmp is unsafe, consider strncmp or strlcmp

2025-04-29 15:31 UTC, themiron commented on accel-pppd/radius/radius.c
> +						    u_ip6str(&fr6->gw, gwbuf), fr6->prio);
reason for indent change? it was aligned to (

2025-04-29 16:09 UTC, ChrisHills463 commented
@themiron thank you for the review :pray: I shall work on getting things up to scratch soon.

2025-07-28 10:23 UTC, AndriiFullroot commented on accel-pppd/libnetlink/iputils.c
> +			if (rtnl_rttable_a2n(&tb_id, "main"))
Is it a bug? Shouldn't it be ```rtnl_rttable_a2n(&tb_id, vrf_name)``?
Why not ```strcmp(vrf_name, "main")``` if returning RT_TABLE_MAIN on a false condition?

2025-07-28 12:49 UTC, Chaz6 commented on accel-pppd/radius/radius.c
> +						    u_ip6str(&fr6->gw, gwbuf), fr6->prio);
Probably an accident, will fix!

2025-07-28 13:02 UTC, Chaz6 commented on accel-pppd/ifcfg.c
> +#endif
Should be fixed in 473a4f1

2025-07-28 13:02 UTC, Chaz6 commented on accel-pppd/ipv6/dhcpv6.c
> +#endif
Should be fixed in 473a4f1

2025-07-28 13:02 UTC, Chaz6 commented on accel-pppd/ipv6/dhcpv6.c
> +#endif
Should be fixed in 473a4f1

2025-07-28 13:03 UTC, Chaz6 commented on accel-pppd/libnetlink/iputils.c
> +	__u32 rt_table = RT_TABLE_MAIN;
Should be fixed in 473a4f1

2025-07-28 13:04 UTC, Chaz6 commented on accel-pppd/radius/radius.c
> +						    u_ip6str(&fr6->gw, gwbuf), fr6->prio);
Should be fixed in 473a4f1

2025-07-28 13:05 UTC, Chaz6 commented on accel-pppd/libnetlink/rt_names.c
> +		return;
Should be fixed in 473a4f1

2026-07-06 22:23 UTC, nuclearcat commented
Thanks for the contribution, and apologies it sat open for so long.

Closing this as superseded: the functionality it adds is now in master via the VRF support merged in #294 (commit d4f230af). Framed-Route and Framed-IPv6-Route from RADIUS are installed into the routing table of the VRF named by Accel-VRF-Name — see radius.c (iproute_add/ip6route_add called with the session's vrf_name) and ipvrf_get_table() in libnetlink/iputils.c, which resolves the VRF's table id directly from the kernel via RTM_GETLINK/IFLA_VRF_TABLE instead of vendoring iproute2's rt_names.c.

If you find any gap compared to this patch, please open an issue or a new PR against current master.

2026-07-06 22:23 UTC, closed without merging

2026-07-07 08:49 UTC, ChrisHills463 commented
Thank you! I am sorry that I was not able to see it through to completion.